services:
  mockup-web-service:
    build: .
    ports:
      - "${APP_PORT:-8080}:${APP_PORT:-8080}"
    environment:
      APP_PORT: ${APP_PORT:-8080}
      DB_USERNAME: ${DB_USERNAME:-sa}
      DB_PASSWORD: ${DB_PASSWORD:-}
      DB_CONNECTION_URL: jdbc:h2:tcp://h2-db:1521/practica-4-demjtav
      DB_DRIVER: org.h2.Driver
      DB_DIALECT: org.hibernate.dialect.H2Dialect
    restart: always
    depends_on:
      h2-db:
        condition: service_healthy
    networks:
      - mockup-network
  h2-db:
    image: oscarfonts/h2
    ports:
      - "${DB_APP_PORT:-8082}:${DB_APP_PORT:-8082}"
    environment:
      DB_APP_PORT: ${DB_APP_PORT:-8082}
      H2_OPTIONS: "-tcp -tcpPort 1521 -web -webAllowOthers -webPort ${DB_APP_PORT:-8082} -ifNotExists"
      LOCAL_VOLUME_PATH: ${LOCAL_VOLUME_PATH:-mockup_data}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${DB_APP_PORT:-8082}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ${LOCAL_VOLUME_PATH:-mockup_data}:/opt/h2-data
    networks:
      - mockup-network

volumes:
    mockup_data:
      driver: local

networks:
  mockup-network:
    driver: bridge