# It wasn't necessary to use docker-compose, but because the assignment said to use it, we did.

services:
    practica-8:
      build: .
      ports:
        - "${APP_PORT:-8080}:${APP_PORT:-8080}"
      environment:
        APP_PORT: ${APP_PORT:-8080}
        DB_USERNAME: ${DB_USERNAME:-sa}
        DB_PASSWORD: ${DB_PASSWORD:-}
        DB_CONNECTION_URL: jdbc:h2:file:~/practica-8-demjtav
        DB_DRIVER: org.h2.Driver
        DB_DIALECT: org.hibernate.dialect.H2Dialect
        RESEND_API_KEY: ${RESEND_API_KEY:-}
        TIME_ZONE: ${TIME_ZONE:-"America/Santo_Domingo"}
      restart: always