FROM haproxy:3.1.5-alpine

USER root

COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
COPY haproxy.pem /etc/haproxy/ssl/haproxy.pem

RUN chown -R haproxy:haproxy /usr/local/etc/haproxy
USER haproxy